const restaurantList = [
  {
    id: 1,
    restaurant_name: "Spice Garden",
    cuisine: "Indian",
    ratings: 4.5,
    images: "https://via.placeholder.com/150?text=Spice+Garden",
  },
  {
    id: 2,
    restaurant_name: "Pasta Palace",
    cuisine: "Italian",
    ratings: 4.2,
    images: "https://via.placeholder.com/150?text=Pasta+Palace",
  },
  {
    id: 3,
    restaurant_name: "Sushi Zen",
    cuisine: "Japanese",
    ratings: 4.8,
    images: "https://via.placeholder.com/150?text=Sushi+Zen",
  },
  {
    id: 4,
    restaurant_name: "Taco Fiesta",
    cuisine: "Mexican",
    ratings: 4.0,
    images: "https://via.placeholder.com/150?text=Taco+Fiesta",
  },
  {
    id: 5,
    restaurant_name: "Burger Hub",
    cuisine: "American",
    ratings: 3.9,
    images: "https://via.placeholder.com/150?text=Burger+Hub",
  },
  {
    id: 6,
    restaurant_name: "Dragon Bowl",
    cuisine: "Chinese",
    ratings: 4.3,
    images: "https://via.placeholder.com/150?text=Dragon+Bowl",
  },
  {
    id: 7,
    restaurant_name: "Mediterraneo",
    cuisine: "Mediterranean",
    ratings: 4.7,
    images: "https://via.placeholder.com/150?text=Mediterraneo",
  },
  {
    id: 8,
    restaurant_name: "Curry House",
    cuisine: "Indian",
    ratings: 4.1,
    images: "https://via.placeholder.com/150?text=Curry+House",
  },
  {
    id: 9,
    restaurant_name: "Bella Napoli",
    cuisine: "Italian",
    ratings: 4.6,
    images: "https://via.placeholder.com/150?text=Bella+Napoli",
  },
  {
    id: 10,
    restaurant_name: "Wok This Way",
    cuisine: "Thai",
    ratings: 4.4,
    images: "https://via.placeholder.com/150?text=Wok+This+Way",
  },
  {
    id: 11,
    restaurant_name: "BBQ Express",
    cuisine: "American",
    ratings: 4.0,
    images: "https://via.placeholder.com/150?text=BBQ+Express",
  },
  {
    id: 12,
    restaurant_name: "Falafel Corner",
    cuisine: "Middle Eastern",
    ratings: 3.8,
    images: "https://via.placeholder.com/150?text=Falafel+Corner",
  },
  {
    id: 13,
    restaurant_name: "Pho Real",
    cuisine: "Vietnamese",
    ratings: 4.5,
    images: "https://via.placeholder.com/150?text=Pho+Real",
  },
  {
    id: 14,
    restaurant_name: "Gyoza Grill",
    cuisine: "Japanese",
    ratings: 4.2,
    images: "https://via.placeholder.com/150?text=Gyoza+Grill",
  },
  {
    id: 15,
    restaurant_name: "La Crêpe",
    cuisine: "French",
    ratings: 4.6,
    images: "https://via.placeholder.com/150?text=La+Crepe",
  },
];


export default restaurantList
